# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ok2pus < Formula
  desc "Terminal-based SSH connection manager"
  homepage "https://github.com/dhrgodms/ok2pus"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dhrgodms/ok2pus/releases/download/v1.0.2/ok2pus_darwin_amd64.tar.gz"
      sha256 "716c2d050862c9db8c6d5a0d1f3d5abe233960620729167c42ab26e23a622c91"

      def install
        bin.install "ok2pus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dhrgodms/ok2pus/releases/download/v1.0.2/ok2pus_darwin_arm64.tar.gz"
      sha256 "804b941ac2f44526eb696c5c4283ca031984335592f3b3889031e9f5ac0dc814"

      def install
        bin.install "ok2pus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhrgodms/ok2pus/releases/download/v1.0.2/ok2pus_linux_amd64.tar.gz"
      sha256 "ee3cf70264dc63ab62354135bced8e8a4a6535abe882834c47081d112069c077"
      def install
        bin.install "ok2pus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhrgodms/ok2pus/releases/download/v1.0.2/ok2pus_linux_arm64.tar.gz"
      sha256 "319db3228368bb0a3269dc676e83eeb298d5ca206781eec45f22fa93bb51c22b"
      def install
        bin.install "ok2pus"
      end
    end
  end
end
