# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ok2pus < Formula
  desc "Terminal-based SSH connection manager"
  homepage "https://github.com/dhrgodms/ok2pus"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dhrgodms/ok2pus/releases/download/v1.0.3/ok2pus_darwin_amd64.tar.gz"
      sha256 "84e0e9e0abfdb4744b3e1608adb0dd81b6ca69051b4ae907161f33548f4c134a"

      def install
        bin.install "ok2pus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dhrgodms/ok2pus/releases/download/v1.0.3/ok2pus_darwin_arm64.tar.gz"
      sha256 "660a4a97d1951b5957a8779d130e94e10d71f63ccbf7a885239edf95b7c1954b"

      def install
        bin.install "ok2pus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhrgodms/ok2pus/releases/download/v1.0.3/ok2pus_linux_amd64.tar.gz"
      sha256 "572995b5ca879afb075d2306eeae52accf4bf065406a6c19e46f60eeade7cf8f"
      def install
        bin.install "ok2pus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhrgodms/ok2pus/releases/download/v1.0.3/ok2pus_linux_arm64.tar.gz"
      sha256 "f1521367749d4701d9406432d863477282e59b6ebff0c13493d797642a05a7ab"
      def install
        bin.install "ok2pus"
      end
    end
  end
end
