# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ok2pus < Formula
  desc "Terminal-based SSH connection manager"
  homepage "https://github.com/dhrgodms/ok2pus"
  version "1.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dhrgodms/ok2pus/releases/download/v1.0.4/ok2pus_darwin_amd64.tar.gz"
      sha256 "f3747dcbc0f0d08dbf7bd4a5291eeea3912f71ff022ad6d20cecb3d7ca089657"

      def install
        bin.install "ok2pus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dhrgodms/ok2pus/releases/download/v1.0.4/ok2pus_darwin_arm64.tar.gz"
      sha256 "ebc7a1833af0e138a162a56ce638a8dec202f3188bbac4d41eda19040dbf8f14"

      def install
        bin.install "ok2pus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhrgodms/ok2pus/releases/download/v1.0.4/ok2pus_linux_amd64.tar.gz"
      sha256 "81ae2de9999a6073b7f7dc003c948a9789cff4b2183673e7b68faed1f52e8d02"
      def install
        bin.install "ok2pus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhrgodms/ok2pus/releases/download/v1.0.4/ok2pus_linux_arm64.tar.gz"
      sha256 "25b5e1b548da68894ecff0529f1064dd55fb6813a25d7047ec2c0dc5ea77b87e"
      def install
        bin.install "ok2pus"
      end
    end
  end
end
