# This file was generated by GoReleaser. DO NOT EDIT.
cask "ok2pus" do
  name "ok2pus"
  desc "Terminal-based SSH connection manager"
  homepage "https://github.com/dhrgodms/ok2pus"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ok2pus"

  on_macos do
    on_intel do
      url "https://github.com/dhrgodms/ok2pus/releases/download/v#{version}/ok2pus_darwin_amd64.tar.gz"
      sha256 "d645a74974c8c7b640abf1fa9ea40a2e35584906ca10c69d016271d9fcc67337"
    end
    on_arm do
      url "https://github.com/dhrgodms/ok2pus/releases/download/v#{version}/ok2pus_darwin_arm64.tar.gz"
      sha256 "eb59503d510c225d5373df7ec54b1817ec014ebc62030d9a93fa4d0d2fdc799d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dhrgodms/ok2pus/releases/download/v#{version}/ok2pus_linux_amd64.tar.gz"
      sha256 "8ce9d4420d41d1260d87b000ac0d72ff77c2ab849ba7fd16353262d9200bad36"
    end
    on_arm do
      url "https://github.com/dhrgodms/ok2pus/releases/download/v#{version}/ok2pus_linux_arm64.tar.gz"
      sha256 "5e820605266bc124018921e11165931115450db74dcf23339fde33b64a7962ef"
    end
  end

  # No zap stanza required
end
