# This file was generated by GoReleaser. DO NOT EDIT.
cask "ok2pus" do
  name "ok2pus"
  desc "Terminal-based SSH connection manager"
  homepage "https://github.com/dhrgodms/ok2pus"
  version "1.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ok2pus"

  on_macos do
    on_intel do
      url "https://github.com/dhrgodms/ok2pus/releases/download/v#{version}/ok2pus_darwin_amd64.tar.gz"
      sha256 "b23093c16fe05d482c0e83e9acda6995552dabef58a88c12bc09cbd50afad741"
    end
    on_arm do
      url "https://github.com/dhrgodms/ok2pus/releases/download/v#{version}/ok2pus_darwin_arm64.tar.gz"
      sha256 "35a880b8e056047ce28bd0d825b964875a750e08400711c187de3fe08c860f2c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dhrgodms/ok2pus/releases/download/v#{version}/ok2pus_linux_amd64.tar.gz"
      sha256 "673597196e16f5937c0e25d18f536709c7fb09fdfc05f5bdceb28cb407d37ca7"
    end
    on_arm do
      url "https://github.com/dhrgodms/ok2pus/releases/download/v#{version}/ok2pus_linux_arm64.tar.gz"
      sha256 "60221b3c30174e67545f6dffbae0d5f68214ff296ca6c352b3d277b76720d361"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ok2pus"]
    end
  end

  # No zap stanza required
end
