# This file was generated by GoReleaser. DO NOT EDIT.
cask "ok2pus" do
  name "ok2pus"
  desc "Terminal-based SSH connection manager"
  homepage "https://github.com/dhrgodms/ok2pus"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ok2pus"

  on_macos do
    on_intel do
      url "https://github.com/dhrgodms/ok2pus/releases/download/v#{version}/ok2pus_darwin_amd64.tar.gz"
      sha256 "6d5e6590a9c06278fbf1619ef61740531fba3554380d14420828cb91e2504832"
    end
    on_arm do
      url "https://github.com/dhrgodms/ok2pus/releases/download/v#{version}/ok2pus_darwin_arm64.tar.gz"
      sha256 "7248cdb9449238b8ccacd00a29f10a20c97a02d62234943066fa44fa49463f73"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dhrgodms/ok2pus/releases/download/v#{version}/ok2pus_linux_amd64.tar.gz"
      sha256 "1a1b18150f2b570baa097dbc69a221642e9fbe435f17ca48730a3fa61429b4c5"
    end
    on_arm do
      url "https://github.com/dhrgodms/ok2pus/releases/download/v#{version}/ok2pus_linux_arm64.tar.gz"
      sha256 "bc67a44c31d69c043872030aab51502704ba23a55e41b495bc9c498074a5fb5b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ok2pus"]
    end
  end

  # No zap stanza required
end
